[package]
name = "end-to-end"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
reqwest = { version = "0.11.14", features = ["json"] }
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive", "env"] }
hyper = { version = "0.14.23", features = ["h2"] }
insta = { version = "1.26.0", features = ["json"] }
octopod = { git = "https://github.com/MarinPostma/octopod.git", rev = "68c24e3" }
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[[test]]
name = "end-to-end"
path = "integration/main.rs"
harness = false
