version: "3.9"
services:
  writer:
    build: ..
    environment:
      - SQLD_NODE=primary
      - SQLD_ENABLE_BOTTOMLESS_REPLICATION=true
      - LIBSQL_BOTTOMLESS_ENDPOINT=http://s3:9000
      - LIBSQL_BOTTOMLESS_AWS_ACCESS_KEY_ID=minioadmin
      - LIBSQL_BOTTOMLESS_AWS_SECRET_ACCESS_KEY=minioadmin
      - LIBSQL_BOTTOMLESS_AWS_DEFAULT_REGION=eu-central-2
      - RUST_LOG=info,bottomless=trace
    ports:
      - "6000:5000"
    depends_on:
      - s3
  reader:
    build: ..
    environment:
      - SQLD_NODE=replica
      - SQLD_PRIMARY_URL=http://writer:5001
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
    depends_on:
      - writer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reader
    ports:
      - "6001:6001"
      - "8080:8080"
  s3:
    image: fclairamb/minio-github-actions
    ports:
      - "9000:9000"
